# Generated by Django 5.0.6 on 2024-06-14 15:42

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Smena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название смены')),
                ('start_at', models.DateField(verbose_name='Начало')),
                ('end_at', models.DateField(verbose_name='Конец')),
                ('is_curent', models.BooleanField(verbose_name='Текущая')),
            ],
        ),
        migrations.CreateModel(
            name='SocialOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='StudyPlaceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название отряда')),
                ('smena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partys', to='data.smena', verbose_name='Смена')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('third_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('sex', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('live_place_full', models.CharField(max_length=255, verbose_name='Место жительства (полностью)')),
                ('region', models.CharField(choices=[('1', 'Брестская область'), ('2', 'Витебская область'), ('3', 'Гомельская область'), ('4', 'Гродненская область'), ('5', 'Минская область'), ('5', 'Могилевская область'), ('6', 'Город Минск')], max_length=1, verbose_name='Область')),
                ('from_city', models.BooleanField(verbose_name='Из города')),
                ('study_place_full', models.CharField(max_length=255, verbose_name='Место обучение (полностью)')),
                ('order_number', models.CharField(max_length=255, verbose_name='Номер путевки')),
                ('order_state', models.CharField(max_length=255, verbose_name='Кем выдана')),
                ('mother_full_name', models.CharField(max_length=255, verbose_name='Полное имя матери')),
                ('mother_birth_date', models.DateField(verbose_name='Дата рождения матери')),
                ('mother_work', models.CharField(max_length=255, verbose_name='Место работы матери')),
                ('mother_post', models.CharField(max_length=255, verbose_name='Должность матери')),
                ('mother_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона матери')),
                ('father_full_name', models.CharField(max_length=255, verbose_name='Полное имя отца')),
                ('father_birth_date', models.DateField(verbose_name='Дата рождения отца')),
                ('father_work', models.CharField(max_length=255, verbose_name='Место работы отца')),
                ('father_post', models.CharField(max_length=255, verbose_name='Должность отца')),
                ('father_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона отца')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('party', models.ManyToManyField(to='data.party', verbose_name='Отряд')),
                ('social_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='data.socialoption', verbose_name='Социальный статус')),
                ('study_place_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='data.studyplaceoption', verbose_name='Тип учебного заведения')),
            ],
        ),
    ]
