# Generated by Django 5.0.6 on 2024-06-14 16:07

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'Воспитаник', 'verbose_name_plural': 'Воспитаники'},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name': 'Отряд', 'verbose_name_plural': 'Отряды'},
        ),
        migrations.AlterModelOptions(
            name='smena',
            options={'verbose_name': 'Смена', 'verbose_name_plural': 'Смены'},
        ),
        migrations.AlterModelOptions(
            name='socialoption',
            options={'verbose_name': 'Социальный статус', 'verbose_name_plural': 'Социальные статусы'},
        ),
        migrations.AlterModelOptions(
            name='studyplaceoption',
            options={'verbose_name': 'Тип учереждения образования', 'verbose_name_plural': 'Типы учереждений образования'},
        ),
        migrations.AlterField(
            model_name='child',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='child',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='child',
            name='father_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения отца'),
        ),
        migrations.AlterField(
            model_name='child',
            name='father_full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное имя отца'),
        ),
        migrations.AlterField(
            model_name='child',
            name='father_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер телефона отца'),
        ),
        migrations.AlterField(
            model_name='child',
            name='father_post',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность отца'),
        ),
        migrations.AlterField(
            model_name='child',
            name='father_work',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место работы отца'),
        ),
        migrations.AlterField(
            model_name='child',
            name='live_place_full',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место жительства (полностью)'),
        ),
        migrations.AlterField(
            model_name='child',
            name='mother_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения матери'),
        ),
        migrations.AlterField(
            model_name='child',
            name='mother_full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное имя матери'),
        ),
        migrations.AlterField(
            model_name='child',
            name='mother_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер телефона матери'),
        ),
        migrations.AlterField(
            model_name='child',
            name='mother_post',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность матери'),
        ),
        migrations.AlterField(
            model_name='child',
            name='mother_work',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место работы матери'),
        ),
        migrations.AlterField(
            model_name='child',
            name='order_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер путевки'),
        ),
        migrations.AlterField(
            model_name='child',
            name='order_state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Кем выдана'),
        ),
        migrations.AlterField(
            model_name='child',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='child',
            name='region',
            field=models.CharField(blank=True, choices=[('1', 'Брестская область'), ('2', 'Витебская область'), ('3', 'Гомельская область'), ('4', 'Гродненская область'), ('5', 'Минская область'), ('5', 'Могилевская область'), ('6', 'Город Минск')], max_length=1, null=True, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='child',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='child',
            name='social_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='data.socialoption', verbose_name='Социальный статус'),
        ),
        migrations.AlterField(
            model_name='child',
            name='study_place_full',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место обучение (полностью)'),
        ),
        migrations.AlterField(
            model_name='child',
            name='study_place_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='data.studyplaceoption', verbose_name='Тип учебного заведения'),
        ),
        migrations.AlterField(
            model_name='smena',
            name='is_curent',
            field=models.BooleanField(verbose_name='Текущая смена'),
        ),
    ]
